- LICENSE
* Created file with Apache 2.0 License
> [DXP-1313] Create LICENSE

- composer.json
DXP-1313 Add license info to composer.json to make the Connector a valid Packagist package
> DXP-1313 Add license info to composer.json

- README.md
> Improved README.md - added composer installation step

- src/catalog/Model/SlugGenerator.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- src/core/test/Model/Indexer/DataProvider/Category/CategoryDataFormatterTest.php
- src/core/test/Model/Indexer/DataProvider/Product/AttributeDataTest.php
> DXP-1310 Rename setting to use_url_key_and_id_to_generate_slug

- src/catalog/Model/SlugGenerator.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- src/core/test/Model/Indexer/DataProvider/Category/CategoryDataFormatterTest.php
- src/core/test/Model/Indexer/DataProvider/Product/AttributeDataTest.php
> DXP-1310 Rename setting to use_url_key_to_generate_slug

- how-to-run-streamx-indexers.md
Add readme how to run streamx indexers
> DXP-1310 Add readme how to run streamx indexers

- src/catalog/Model/Config/Source/Product/ProductType.php
- src/catalog/Model/ResourceModel/Product.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
DXP-1451 Remove publishing downloadable products
> DXP-1451 Remove publishing downloadable products

- src/catalog/Model/ResourceModel/Category.php
Make query for category name and url-key universal on all Magento versions
> DXP-1451 Make query for category name and url-key universal on all Magento versions

- composer.json
Bump connector version to 1.0.1
> DXP-1310 Bump connector version to 1.0.1

- src/catalog/Model/Indexer/DataProvider/Product/AttributeData.php
- src/catalog/test/resources/validation/edited-bag-product.json
- src/catalog/test/resources/validation/edited-hoodie-product.json
- src/catalog/test/resources/validation/original-bag-product.json
- src/catalog/test/resources/validation/original-hoodie-product.json
- src/core/Indexer/ImageUrlManager.php
> DXP-1451 Publish also images from attributes with full urls

- connector-test-tools/Impl/EntityAddControllerImpl.php
> DXP-1451 Stabilize integration test by adding product and category assignment in transaction

- src/catalog/Model/Indexer/DataProvider/Product/AttributeData.php
- src/catalog/test/troubleshoot-mview-update-errors.MD
Troubleshoot internal mview failures and fix cause
> DXP-1451 Troubleshoot internal mview failures and fix cause

- src/catalog/Model/ResourceModel/Category.php
- src/catalog/Model/ResourceModel/Category/ActiveSelectModifier.php
- src/catalog/Model/ResourceModel/Category/Children.php
- src/catalog/Model/ResourceModel/Category/CompositeBaseSelectModifier.php
- src/catalog/Model/ResourceModel/Category/CompositeWithStoreChildrenModifier.php
- src/catalog/Model/ResourceModel/Category/CompositeWithStoreModifier.php
- src/catalog/Model/ResourceModel/Category/LoadAttributes.php
- src/catalog/Model/ResourceModel/Category/SelectModifierInterface.php
- src/catalog/Model/ResourceModel/Category/StoreSelectModifier.php
- src/catalog/etc/di.xml
Move category select modifiers out of di.xml, and do minor improvements in their code
> DXP-1310 Move category select modifiers out of di.xml, and do minor improvements in their code

- connector-test-tools/Impl/EntityAddControllerImpl.php
- src/catalog/Cron/MView/StreamxIndexerMviewProcessor.php
- src/catalog/Model/Attributes/ConfigurableAttributes.php
- src/catalog/Model/Attributes/ProductAttributes.php
- src/catalog/Model/Indexer/DataProvider/Product/AttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php
- src/catalog/Model/ResourceModel/Product/LoadAttributes.php
- src/catalog/Model/ResourceModel/Product/ProductAttributesProvider.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/test/Model/Attributes/ConfigurableAttributesTest.php
- src/catalog/test/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/integration/BaseStreamxConnectorPublishTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/BaseDirectDbEntityUpdateTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/integration/utils/JsonFormatter.php
- src/catalog/test/integration/utils/MagentoIndexerOperationsExecutor.php
- src/catalog/test/resources/validation/added-watch-product.json
Improve indexing all product attributes.
> DXP-1451 Improve indexing all product attributes

- composer.json
- connector-test-tools/Api/ConfigurationEditControllerInterface.php
- connector-test-tools/Impl/ConfigurationEditControllerImpl.php
- connector-test-tools/etc/di.xml
- connector-test-tools/etc/webapi.xml
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/test/integration/BaseStreamxConnectorPublishTest.php
- src/catalog/test/integration/utils/CodeCoverageReportGenerator.php
- src/catalog/test/integration/utils/ConfigurationEditTraits.php
- src/catalog/test/integration/utils/FileUtils.php
- src/catalog/test/integration/utils/MagentoIndexerOperationsExecutor.php
- src/catalog/test/integration/utils/MagentoOperationsExecutor.php
- src/catalog/test/integration/utils/ValidationFileUtils.php
DXP-1310 Improve overriding connector configuration for integration tests
> DXP-1310 Improve overriding connector configuration for integration tests

- connector-test-tools/Impl/EntityAddControllerImpl.php
- src/catalog/Model/Indexer/DataProvider/Product/AttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/ResourceModel/Product/ProductAttributesProvider.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/resources/validation/added-watch-product.json
- src/catalog/test/resources/validation/edited-bag-product.json
- src/catalog/test/resources/validation/edited-hoodie-product.json
- src/catalog/test/resources/validation/original-bag-product.json
- src/catalog/test/resources/validation/original-hoodie-product.json
Handle multivalued product attributes
> DXP-1451 Handle multivalued product attributes

- src/catalog/Model/Config/Source/Product/AbstractAttributeSource.php
- src/catalog/Model/Config/Source/Product/ConfigurableChildAttributes.php
- src/catalog/Model/Config/Source/Product/ProductType.php
- src/catalog/Model/Indexer/DataProvider/Product/CustomOptionConverter.php
- src/catalog/Model/Indexer/DataProvider/Product/CustomOptions.php
- src/catalog/Model/ResourceModel/Category/LoadAttributes.php
> DXP-1451 A few small code improvements

- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/integration/utils/MagentoMySqlQueryExecutor.php
- src/catalog/test/resources/validation/added-watch-product.json
> DXP-1451 Add test for publishing product options

- connector-test-tools/Impl/EntityAddControllerImpl.php
- src/catalog/test/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/resources/validation/added-watch-product-without-custom-options.json
> DXP-1310 Fix failing test

- src/catalog/Model/Indexer/DataProvider/Product/AttributeData.php
- src/catalog/test/resources/validation/added-watch-product-without-custom-options.json
- src/catalog/test/resources/validation/added-watch-product.json
- src/catalog/test/resources/validation/edited-bag-product.json
- src/catalog/test/resources/validation/edited-hoodie-product.json
- src/catalog/test/resources/validation/original-bag-product.json
- src/catalog/test/resources/validation/original-hoodie-product.json
> DXP-1568 Add product label to published payload

- src/catalog/Model/Indexer/DataProvider/Product/Configurable/LoadChildrenRawAttributes.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/QuantityData.php
- src/catalog/Model/Indexer/IndexersConfig.php
- src/catalog/Model/ResourceModel/Product/Configurable.php
- src/catalog/test/resources/validation/edited-hoodie-product.json
- src/catalog/test/resources/validation/original-hoodie-product.json
> DXP-1566 Remove prices from product variants

- src/catalog/Model/Attributes/ConfigurableAttributes.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseMediaGalleryData.php
- src/catalog/Model/Indexer/DataProvider/Product/ChildProductMediaGalleryData.php
- src/catalog/Model/Indexer/DataProvider/Product/Configurable/LoadChildrenRawAttributes.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/ProductMediaGalleryData.php
- src/catalog/Model/Indexer/IndexersConfig.php
- src/catalog/Model/Product/LoadMediaGallery.php
- src/catalog/test/resources/validation/edited-hoodie-product.json
- src/catalog/test/resources/validation/original-hoodie-product.json
- src/core/Api/DataProviderInterface.php
> DXP-1566 Use common gallery provider also for variant products

- connector-test-tools/Impl/CoverageMeasurementTraits.php
- how-to-debug-connector-code-on-magento.md
> DXP-1568 Add instruction how to debug connector code

- README.md
- how-to-use-streamx-connector-in-magento.md
- src/catalog/test/troubleshoot-mview-update-errors.MD
Enable using StreamX Magento Connector as a standard composer dependency
> DXP-1310 Add Readme for using StreamX Magento Connector as a standard composer dependency

- src/catalog/Model/Attribute/LoadOptions.php
- src/catalog/Model/Indexer/IndexersConfig.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
> DXP-1568 Remove unused configuration settings. Review TODOs

- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/test/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- src/catalog/test/resources/validation/edited-bundle-product.json
- src/catalog/test/resources/validation/original-bundle-product.json
> DXP-1451 Add test for publishing bundleproducts

- src/catalog/test/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- src/catalog/test/resources/validation/edited-grouped-product.json
- src/catalog/test/resources/validation/original-grouped-product.json
> DXP-1451 Add test for publishing group products

- how-to-debug-connector-code-on-magento.md
- src/catalog/test/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- src/catalog/test/integration/BaseStreamxConnectorPublishTest.php
- src/catalog/test/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
> DXP-1567 Configure debugging connector code without the need to use a web browser

- composer.json
> DXP-1605 Exclude test classes from di:compile

- how-to-debug-connector-code-on-magento.md
- src/catalog/Indexer/AttributeIndexerHandler.php
- src/catalog/Indexer/CategoryIndexerHandler.php
- src/catalog/Indexer/ProductIndexerHandler.php
- src/catalog/Model/Indexer/BaseStreamxIndexer.php
- src/core/Indexer/GenericIndexerHandler.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/resources/validation/edited-description-attribute.json
- test/resources/validation/edited-size-attribute.json
> DXP-1567 A few small improvements

- README.md
> DXP-1568 Fix numbering in readme

- connector-test-tools/Impl/EntityEditControllerImpl.php
- src/catalog/Indexer/ProductIndexerHandler.php
- src/catalog/Model/Indexer/Action/Attribute.php
- src/catalog/Model/Indexer/DataProvider/Attribute/ProductsWithChangedAttributesProvider.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/ChildProductAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/ProductAttributeData.php
- src/catalog/Model/ResourceModel/Product/Configurable.php
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- src/catalog/Model/ResourceModel/ProductConfig.php
- src/catalog/etc/mview.xml
> DXP-1567 Avoid loading non product attributes

- src/catalog/Model/Indexer/Action/Attribute.php
- src/catalog/Model/SlugGenerator.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
> DXP-1567 Add test for which products are published on variant or parent change

- src/catalog/Model/Indexer/Action/Product.php
- src/catalog/Model/ResourceModel/Product.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/core/unit/Model/Indexer/DataProvider/Product/ProductAttributeDataTest.php
> DXP-1567 Publish only parent product when variant is edited

- composer.json
- src/core/Api/Client/ConfigurationInterface.php
- src/core/Streamx/ClientConfiguration.php
- src/core/Streamx/ClientResolver.php
- src/core/Streamx/StreamxPublisherProvider.php
- src/core/etc/adminhtml/system.xml
- src/core/etc/config.xml
> DXP-1568 Allow skipping certificate validation

- src/catalog/Model/Attribute/LoadOptions.php
- src/catalog/Model/Attribute/OptionCollectionToArray.php
> DXP-1577 Shorten code for processing options array

- src/catalog/Plugin/Controller/Catalog/Adminhtml/Product/Action/AttributeSavePlugin.php
- src/catalog/Plugin/Indexer/CatalogInventory/QtyCorrectPlugin.php
- src/catalog/Plugin/Indexer/CatalogInventory/ReindexQuoteInventoryObserverPlugin.php
- src/catalog/Plugin/Indexer/CatalogInventory/RevertQuoteInventoryObserverPlugin.php
- src/catalog/Plugin/Indexer/Category/Save/UpdateCategoryDataPlugin.php
- src/catalog/Plugin/Mview/ViewPlugin.php
- src/catalog/etc/di.xml
> DXP-1568 Remove last instances of "es" naming. Add TODOs for uncovered areas

- src/catalog/Model/Indexer/Action/BaseAction.php
- src/catalog/Model/Indexer/Action/Product.php
- src/catalog/Model/ResourceModel/Product.php
> DXP-1567 Skip publishing variants as separate publishes in product indexer

- src/catalog/Model/Attribute/LoadOptions.php
- src/catalog/Model/ResourceModel/Product/Configurable.php
- src/catalog/Model/ResourceModel/Product/LoadAttributes.php
- src/catalog/Model/ResourceModel/Product/ProductAttributesProvider.php
- src/catalog/Model/ResourceModel/Product/StatusSelectModifier.php
> DXP-1579 Make ProductAttributesProvider be used only by product data providers

- src/catalog/Model/Attribute/OptionCollectionToArray.php
- src/catalog/Model/Attributes/AttributeOptionDefinition.php
- src/catalog/Model/Attributes/AttributeOptionSwatchDefinition.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- test/resources/validation/added-watch-product-without-custom-options.json
- test/resources/validation/added-watch-product.json
- test/resources/validation/edited-hoodie-product.json
- test/resources/validation/original-hoodie-product.json
> DXP-1577 Publish attribute option swatches

- connector-test-tools/Impl/EntityAddControllerImpl.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/PriceData.php
- src/catalog/Model/Indexer/IndexersConfig.php
- src/catalog/Model/Product/PriceTableResolverProxy.php
- src/catalog/Model/ResourceModel/Product/Prices.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/resources/validation/added-watch-product-without-custom-options.json
- test/resources/validation/added-watch-product.json
- test/resources/validation/edited-bag-product.json
- test/resources/validation/edited-bundle-product.json
- test/resources/validation/edited-hoodie-product.json
- test/resources/validation/original-bag-product.json
- test/resources/validation/original-bundle-product.json
- test/resources/validation/original-hoodie-product.json
> DXP-1577 Extend product price payload to publish also discounted price

- src/catalog/Model/Attributes/ChildProductAttributes.php
- src/catalog/Model/Attributes/ProductAttributes.php
- src/catalog/Model/Config/Source/Product/ConfigurableChildProductAttributes.php
- src/catalog/Model/Config/Source/Product/ConfigurableProductAttributes.php
- src/catalog/Model/Indexer/DataProvider/Product/ChildProductMediaGalleryData.php
- src/catalog/Model/Indexer/DataProvider/Product/ProductMediaGalleryData.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- test/catalog/integration/utils/ConfigurationEditTraits.php
> DXP-1579 Improve naming for main and child products cfg classes

- src/catalog/Cron/MView/StreamxIndexerMviewProcessor.php
- src/catalog/Model/Attributes/BaseProductAttributes.php
- src/catalog/Model/Config/Source/Product/AbstractAttributeSource.php
- src/catalog/Model/Indexer/Action/BaseAction.php
- src/catalog/Model/Indexer/Action/Product.php
- src/catalog/Model/ResourceModel/Category.php
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- src/catalog/Model/ResourceModel/Product/ProductAttributesProvider.php
- src/catalog/Model/SlugGenerator.php
- src/core/Api/DataProviderInterface.php
> DXP-1568 Improve documentation tags

- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/core/Api/BaseConfigurationManager.php
- src/core/Api/BaseConfigurationReader.php
- src/core/Config/OptimizationSettings.php
- src/core/Streamx/Client.php
- src/core/Streamx/ClientConfiguration.php
- src/core/System/GeneralConfig.php
- src/core/etc/adminhtml/events.xml
- src/core/etc/adminhtml/system.xml
- src/core/view/adminhtml/requirejs-config.js
- src/core/view/adminhtml/web/js/ui-config-validation/validate-between-1-and-500.js
> DXP-1568 Force value range for batch indexing size

- src/catalog/Model/Indexer/Attribute.php
- src/catalog/Model/Indexer/BaseStreamxIndexer.php
- src/catalog/Model/Indexer/Category.php
- src/catalog/Model/Indexer/Product.php
- src/core/Console/Command/PublishAllEntitiesCommand.php
- src/core/Console/Command/PublishSingleEntityCommand.php
- src/core/Indexer/IndexableStoresProvider.php
> DXP-1633 Give IndexableStoresProvider name distinct from Magento's StoreManager class

- src/core/Console/Command/PublishAllEntitiesCommand.php
- src/core/Console/Command/PublishSingleEntityCommand.php
> DXP-1633 Unify declarations of StoreManager

- composer.json
- src/catalog/Model/Indexer/Action/Attribute.php
- src/catalog/Model/Indexer/Action/BaseAction.php
- src/catalog/Model/Indexer/Action/Category.php
- src/catalog/Model/Indexer/Action/Product.php
- src/catalog/Model/Indexer/BaseStreamxIndexer.php
- src/catalog/Model/Indexer/DataProvider/Product/CategoryData.php
- src/catalog/Model/ResourceModel/Category.php
- src/catalog/Model/ResourceModel/Product.php
- src/core/Api/BaseConfigurationManager.php
- src/core/Config/OptimizationSettings.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/resources/validation/added-minimal-product.json
> DXP-1633 Allow for product to not have any active category in the store being indexed

- connector-test-tools/Api/EntityAddControllerInterface.php
- connector-test-tools/Impl/EntityAddControllerImpl.php
- src/catalog/Model/ResourceModel/Category.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/resources/validation/added-watch-product-without-custom-options.json
- test/resources/validation/added-watch-product.json
- test/resources/validation/edited-hoodie-product.json
- test/resources/validation/original-hoodie-product.json
> DXP-1633 Skip publishing not active categories of a product

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/BaseMultistoreTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/resources/validation/added-category.json
- test/resources/validation/added-minimal-product.json
- test/resources/validation/bag-with-edited-category.json
…published; make remaining tests fully verify published jsons
* ...
* ...
> DXP-1633 Make sure store-specific category data will be selected and published; make remaining tests fully verify published jsons

- how-to-setup-local-development-environment.md
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/resources/validation/edited-description-attribute.json
- test/resources/validation/edited-size-attribute.json
- test/resources/validation/original-description-attribute.json
- test/resources/validation/original-size-attribute.json
- test/resources/validation/wayfarer-bag-product.json
> DXP-1633 Improve multiwebsite test

- src/core/Streamx/StreamxPublisherProvider.php
> DXP-1633 Protect against possible freeze of StreamX client

- src/catalog/Cron/MView/StreamxIndexerMviewProcessor.php
> DXP-1633 Don't attempt to execute mview-based indexers from cron, if they are currently in the Update On Save mode

- src/core/Streamx/Client.php
- test/catalog/integration/BaseStreamxTest.php
> DXP-1633 Improve ingestion log messages and improve deleting data in test preconditions

- phpunit.xml
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/StreamxConnectorClientAvailabilityTest.php
> DXP-1633 Add unit test for publishing big batch of data

- how-to-setup-local-development-environment.md
> DXP-1568 Add troubleshooting local env info to readme

- src/core/Client/StreamxClient.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryAddAndDeleteTest.php
> DXP-1633 Improve exception logging

- connector-test-tools/Api/StoresControllerInterface.php
- connector-test-tools/Impl/StoresControllerImpl.php
- connector-test-tools/etc/di.xml
- connector-test-tools/etc/webapi.xml
- how-to-debug-connector-code-on-magento.md
- how-to-setup-local-development-environment.md
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/BaseMultistoreTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/utils/ConfigurationEditTraits.php
- test/catalog/integration/utils/MagentoIndexerOperationsExecutor.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/catalog/integration/utils/MagentoOperationsExecutor.php
> DXP-1633 Automate creating stores for multistore tests

- src/catalog/etc/crontab.xml
> DXP-1578 Execute mview reindexing less often

- composer.json
- src/catalog/Model/Attribute/LoadOptions.php
- src/catalog/Model/Attribute/OptionCollectionToArray.php
- src/catalog/Model/Attributes/AttributeDefinition.php
- src/catalog/Model/Attributes/AttributeOptionDefinition.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/SpecialAttributes.php
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- test/resources/validation/added-minimal-product.json
- test/resources/validation/added-watch-product-without-custom-options.json
- test/resources/validation/added-watch-product.json
- test/resources/validation/bag-with-edited-category.json
- test/resources/validation/edited-bag-no-attributes-product.json
- test/resources/validation/edited-bag-product.json
- test/resources/validation/edited-ball-product.json
- test/resources/validation/edited-bundle-product.json
- test/resources/validation/edited-grouped-product.json
- test/resources/validation/edited-hoodie-product.json
- test/resources/validation/edited-roller-product-with-custom-attribute.json
- test/resources/validation/original-bag-no-attributes-product.json
- test/resources/validation/original-bag-product.json
- test/resources/validation/original-ball-product.json
- test/resources/validation/original-bundle-product.json
- test/resources/validation/original-grouped-product.json
- test/resources/validation/original-hoodie-product.json
- test/resources/validation/wayfarer-bag-product.json
> DXP-1568 Change format of publishing values of attributes and options

- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/ProductDescriptionUnwrapper.php
- test/core/unit/Model/Indexer/DataProvider/Category/CategoryDataFormatterTest.php
- test/core/unit/Model/Indexer/DataProvider/Product/ProductAttributeDataTest.php
- test/core/unit/Model/Indexer/DataProvider/Product/ProductDescriptionUnwrapperTest.php
> DXP-1675 Unwrap and decode product description

- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Indexer/CategoriesIndexer.php
- src/catalog/Indexer/ProductsIndexer.php
- src/catalog/Model/Indexer/DataLoader/AttributeDataLoader.php
- src/catalog/Model/Indexer/DataLoader/CategoryDataLoader.php
- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/catalog/Model/Indexer/DataProvider/Attribute/ProductsWithChangedAttributesIndexer.php
- src/core/Api/BasicDataLoader.php
- src/core/Indexer/BaseStreamxIndexer.php
> DXP-1672 Rename basic data loaders

- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/utils/ConfigurationEditTraits.php
> DXP-1655 Speed up integration tests

- src/core/Indexer/ImageUrlManager.php
> DXP-1689 Use secure base url when exporting paths of images

- composer.json
- src/catalog/Model/Attributes/AttributeDefinition.php
- src/catalog/Model/Indexer/DataProvider/Attribute/ProductsWithChangedAttributesIndexer.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- test/resources/validation/added-minimal-product.json
- test/resources/validation/added-watch-product-without-custom-options.json
- test/resources/validation/added-watch-product.json
- test/resources/validation/bag-with-edited-category.json
- test/resources/validation/edited-bag-no-attributes-product.json
- test/resources/validation/edited-bag-product.json
- test/resources/validation/edited-ball-product.json
- test/resources/validation/edited-bundle-product.json
- test/resources/validation/edited-grouped-product.json
- test/resources/validation/edited-hoodie-product.json
- test/resources/validation/edited-roller-product-with-custom-attribute.json
- test/resources/validation/original-bag-no-attributes-product.json
- test/resources/validation/original-bag-product.json
- test/resources/validation/original-ball-product.json
- test/resources/validation/original-bundle-product.json
- test/resources/validation/original-grouped-product.json
- test/resources/validation/original-hoodie-product.json
- test/resources/validation/wayfarer-bag-product.json
> DXP-1568 Publish swatch as part of option value and remove options list

- src/catalog/Model/Indexer/DataProvider/Category/CategoryDataFormatter.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/BundleOptionsData.php
- src/catalog/Model/Indexer/DataProvider/Product/CategoryData.php
- src/catalog/Model/Indexer/DataProvider/Product/ChildProductDataCleaner.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/CustomOptions.php
- src/catalog/Model/Indexer/DataProvider/Product/DataCleaner.php
- src/catalog/Model/Indexer/DataProvider/Product/LangData.php
- src/catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php
- src/catalog/Model/Indexer/DataProvider/Product/PriceData.php
- src/catalog/Model/Indexer/DataProvider/Product/QuantityData.php
- src/core/Api/DataProviderInterface.php
- src/core/Indexer/BaseStreamxIndexer.php
* ...
* ...
- [x Changed code is covered with unit tests
> DXP-1568 Make DataProviders add their data directly

- src/catalog/Model/Attribute/AttributeOptionDefinitionParser.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/BundleOptionsData.php
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
Remove unnecessary nulling of local vars
> DXP-1568 Remove unnecessary nulling of local vars

- src/catalog/Model/ResourceModel/Product.php
- src/catalog/Model/ResourceModel/Product/VisibleSelectModifier.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/utils/ConfigurationEditTraits.php
- test/resources/validation/added-minimal-product.json
Publish products based on visibility
> DXP-1568 Publish products based on visibility

- composer.json
- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/catalog/Model/ResourceModel/Product.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/resources/validation/original-hoodie-xl-orange-product.json
- also publish variants when parent is modified
- also publish parent when variant is modified
> DXP-1672 Trigger additional parent/variants publishing

- connector-test-tools/Impl/StoresControllerImpl.php
- src/catalog/Model/ResourceModel/Product.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/resources/validation/original-hoodie-product-in-second-website.json
- test/resources/validation/original-hoodie-xl-gray-product.json
- test/resources/validation/original-hoodie-xl-orange-product.json
Make sure only variants available in the website are published
> DXP-1672 Make sure only variants available in the website are published

- composer.json
- connector-test-tools/Impl/StoresControllerImpl.php
- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Model/Indexer/DataProvider/Attribute/ProductsWithChangedAttributesIndexer.php
- src/core/Client/EntityType.php
- src/core/Client/StreamxClient.php
- src/core/Client/StreamxClientConfiguration.php
- src/core/Indexer/BaseStreamxIndexer.php
- src/core/etc/adminhtml/system.xml
- src/core/etc/config.xml
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/StreamxConnectorClientAvailabilityTest.php
Publish data with types and autogenerated key prefixes
> DXP-1568 Publish data with types and autogenerated key prefixes

- src/core/Client/StreamxClient.php
Rename streamx:type property to sx:type
> DXP-1568 Rename streamx:type property to sx:type

- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Model/ResourceModel/Product.php
Move code for selecting product ids to correct place
> DXP-1568 Move code for selecting product ids to correct place

- src/catalog/Model/CategoryMetaData.php
- src/catalog/Model/Indexer/DataProvider/Product/CustomOptions.php
- src/catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php
- src/catalog/Model/ProductMetaData.php
- src/catalog/Model/ResourceModel/Category.php
- src/catalog/Model/ResourceModel/Category/ActiveCategorySelectModifier.php
- src/catalog/Model/ResourceModel/Category/Children.php
- src/catalog/Model/ResourceModel/Product.php
- src/catalog/Model/ResourceModel/Product/Bundle.php
- src/catalog/Model/ResourceModel/Product/Configurable.php
- src/catalog/Model/ResourceModel/Product/Gallery.php
- src/catalog/Model/ResourceModel/Product/Prices.php
- src/catalog/Model/ResourceModel/Product/ProductAttributesProvider.php
- src/catalog/Model/ResourceModel/Product/StatusEnabledSelectModifier.php
- src/catalog/Model/ResourceModel/Product/VisibleSelectModifier.php
- src/catalog/Model/ResourceModel/ProductConfig.php
Simplify entity metadata classes
> DXP-1568 Simplify entity metadata classes

- src/catalog/Model/ResourceModel/Product.php
- src/core/Client/EntityType.php
- src/core/Client/StreamxClient.php
> DXP-1713 Cleanup outdated TODO tags

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/StreamxConnectorClientAvailabilityTest.php
- test/catalog/integration/utils/EntityIdsAndName.php
- test/catalog/integration/utils/IngestedKeys.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
Use common object for Entity IDs in tests
> DXP-1565 Use common object for Entity IDs in tests

- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/resources/validation/edited-material-attr-ball-product.json
- test/resources/validation/edited-sale-attr-ball-product.json
Make sure edited attribute label is outputted to json of products that use it
> DXP-1719 Make sure edited attribute label is outputted to json of products that use it

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/utils/ConfigurationEditTraits.php
DXP-1719 Improve configuring exported attributes in tests
> DXP-1719 Improve configuring exported attributes in tests

- composer.json
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductAddAndDeleteTest.php
- test/resources/validation/wayfarer-bag-product.json
Use store-level attribute labels when publishing products
> DXP-1719 Use store-level attribute labels when publishing products

- connector-test-tools/Impl/StoresControllerImpl.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/BaseMultistoreProductVariantIngestionTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreCategoryUnpublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductUnpublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
Adjust naming of stores in tests to improve consistency
> DXP-1719 Adjust naming of stores in tests to improve consistency

- connector-test-tools/Api/EntityAddControllerInterface.php
- connector-test-tools/Impl/EntityAddControllerImpl.php
- connector-test-tools/etc/webapi.xml
- copy-connector-test-tools-to-magento.sh
- install-magento-with-connector.sh
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/MultistoreProductUnpublishTest.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
- test/catalog/integration/utils/ValidationFileUtils.php
- test/resources/validation/edited-roller-product-with-custom-attribute.json
> DXP-1767 Minor improvements

- src/catalog/Model/ResourceModel/Product/Bundle.php
- test/resources/validation/edited-bundle-product.json
- test/resources/validation/original-bundle-product.json
Remove product links from bundle product payload
> DXP-1719 Remove product links from bundle product payload

- src/catalog/Model/CategoryMetaData.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/ResourceModel/Category.php
Load store-level category names
> DXP-1719 Load store-level category names

- scripts/install-magento-with-connector.sh
Remove weak password warning when logging in as test Magento Admin
> DXP-1672 Remove weak password warning when logging in as test Magento Admin

- connector-test-tools/Api/EntityEditControllerInterface.php
- connector-test-tools/Api/MviewReindexerInterface.php
- connector-test-tools/Api/StoresControllerInterface.php
- connector-test-tools/Impl/EndpointCoveredCodeProxyPlugin.php
- connector-test-tools/Impl/EntityEditControllerImpl.php
- connector-test-tools/Impl/MviewReindexerImpl.php
- connector-test-tools/etc/di.xml
- how-to-setup-local-development-environment.md
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/BaseDirectDbEntityUpdateTest.php
- test/catalog/integration/utils/CodeCoverageReportGenerator.php
Improve Connector's code coverage measurement on magento server
> DXP-1719 Improve Connector's code coverage measurement on server

- connector-test-tools/Impl/EndpointCoveredCodeProxyPlugin.php
- how-to-setup-local-development-environment.md
- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/catalog/Model/ResourceModel/Product/Prices.php
- src/catalog/Plugin/Indexer/Category/Save/UpdateCategoryDataPlugin.php
- src/core/Config/OptimizationSettings.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/SummaryCoverageMeasurementTest.php
- test/catalog/integration/utils/CodeCoverageDataMerger.php
- test/catalog/integration/utils/CodeCoverageReportGenerator.php
- test/catalog/integration/utils/FileUtils.php
Introduce mechanism to measure summary coverage of all integration tests
> DXP-1719 Introduce mechanism to measure summary coverage of all integration tests

- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/utils/MagentoIndexerOperationsExecutor.php
Speed up integration tests by querying for original modes of indexes just once
> DXP-1719 Speed up integration tests by querying for original modes of indexes just once

- src/catalog/Model/ResourceModel/Product/Prices.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/Plugin/Mview/ViewPlugin.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductCategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductPricePublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/SummaryCoverageMeasurementTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
Make non-indexed price have higher priority
> DXP-1719 Add test for Catalog Rule Prices

- connector-test-tools/Api/EntityEditControllerInterface.php
- connector-test-tools/Api/PriceIndexerInterface.php
- connector-test-tools/Impl/EntityEditControllerImpl.php
- connector-test-tools/Impl/PriceIndexerImpl.php
- connector-test-tools/etc/di.xml
- connector-test-tools/etc/webapi.xml
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/Indexer/DataProvider/Product/IndexedPricesProvider.php
- src/catalog/Model/Indexer/IndexersConfig.php
- src/catalog/Model/ResourceModel/Product/IndexedPrices.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/Plugin/Mview/ViewPlugin.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductPricePublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductPricePublishTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
Introduce configurability of using prices index (default to false)
> DXP-1839 Introduce configurability of using prices index (default to false)

- connector-test-tools/Impl/EntityEditControllerImpl.php
- src/catalog/Plugin/Controller/Catalog/Adminhtml/Product/Action/AttributeSavePlugin.php
> DXP-1825 Review AttributeSavePlugin

- .github/workflows/bump-project-version.yml
Add github hook to autoupdate version after each merge to main
> DXP-1580 Add github hook to autoupdate version after each merge to main

- .github/workflows/bump-project-version.yml
Github autoupdate version fixes
> DXP-1580 Github autoupdate version fixes

- src/catalog/Plugin/Mview/ViewPlugin.php
> DXP-1825 Review ViewPlugin

- connector-test-tools/Impl/EndpointCoveredCodeProxyPlugin.php
- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Plugin/Indexer/Attribute/Save/UpdateAttributeDataPlugin.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
Handle reindexing products that used a deleted attribute: in UpdateOnSave mode
> DXP-1824 Handle reindexing products that used a deleted attribute: in UpdateOnSave mode

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/utils/MagentoMySqlAttributesHelper.php
- test/catalog/integration/utils/MagentoMySqlQueryExecutor.php
Cleanup/unify code for get/set/delete entity attributes in tests
> DXP-1825 Cleanup/unify code for get/set/delete entity attributes in tests

- connector-test-tools/Api/EntityEditControllerInterface.php
- connector-test-tools/Impl/EntityEditControllerImpl.php
- connector-test-tools/etc/webapi.xml
- src/catalog/Plugin/Indexer/Category/Save/UpdateCategoryDataPlugin.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/resources/validation/edited-tee-product.json
- test/resources/validation/original-tee-product.json
Handle case of admin adding or removing products from edited category
> DXP-1825 Handle case of admin adding or removing products from edited category

- .github/workflows/bump-project-version.yml
Set identity of the pusher to current user
> DXP-1580 Set identity of the pusher to current user

- connector-test-tools/Impl/StoresControllerImpl.php
- scripts/install-magento-with-connector.sh
- src/core/Client/RabbitMQ/BaseRabbitMqIngestionRequestsService.php
- src/core/Client/RabbitMQ/RabbitMqConfiguration.php
- src/core/Client/RabbitMQ/RabbitMqIngestionRequestsConsumer.php
- src/core/Console/Command/RabbitMqIngestionRequestsConsumerStartCommand.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/RabbitMqDeadLetterQueueTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
> Dxp 1681 add dlq support mvp

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/StreamxConnectorClientAvailabilityTest.php
Minor improvements in test code
> DXP-1681 Minor improvements in test code

- src/core/Client/StreamxAvailabilityChecker.php
- src/core/Client/StreamxClient.php
- src/core/Client/StreamxPublisherFactory.php
- src/core/Indexer/BaseStreamxIndexer.php
- src/core/Traits/ExceptionLogger.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/StreamxAvailabilityCheckerTest.php
- test/catalog/integration/StreamxConnectorClientLoadTest.php
Split StreamX Client and Availability Checker
> DXP-1681 Split StreamX Client and Availability Checker

- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Indexer/CategoriesIndexer.php
- src/catalog/Indexer/ProductsIndexer.php
- src/core/Api/BaseConfigurationReader.php
- src/core/Indexer/BaseStreamxIndexer.php
- src/core/System/GeneralConfig.php
- src/core/etc/config.xml
- test/catalog/integration/StreamxAvailabilityCheckerTest.php
Use factories for creating services with injectable dependencies
> DXP-1681 Use factories for creating services with injectable dependencies

- connector-test-tools/Api/StoresControllerInterface.php
- connector-test-tools/Impl/ConfigurationEditControllerImpl.php
- connector-test-tools/Impl/StoresControllerImpl.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductPricePublishTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/catalog/integration/utils/MagentoOperationsExecutor.php
Perform faster serverside cache cleaning
> DXP-1681 Perform faster serverside cache cleaning

- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/core/Client/EntityType.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
Remove TODOs for grouped products - treat the feature as completed
> DXP-1912 Remove TODOs for grouped products - treat the feature as completed

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateWhenChangedProductTypeSettingsTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductVariantUpdateWhenChangedProductTypeSettingsTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
Verify publication when exported product types are limited
> DXP-1912 Verify publication when exported product types are limited

- composer.json
> DXP-1826 Update version to 1.0.17

- src/catalog/Model/Indexer/DataProvider/Category/CategoryDataFormatter.php
- test/catalog/integration/BaseProductImportTest.php
- test/resources/validation/imported/furniture-category.json
- test/resources/validation/original-default-category-with-url-key-slugs.json
- test/resources/validation/original-default-category.json
- test/resources/validation/original-men-category.json
Remove unnecessary fields also from nested subcategories
> DXP-1912 Remove unnecessary fields also from nested subcategories

- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/catalog/Model/ResourceModel/Product.php
Use built-in methods for retrieving variant and parent ids
> DXP-1823 Use built-in methods for retrieving variant and parent ids

- src/catalog/Model/Attribute/LoadOptions.php
- src/catalog/Model/ResourceModel/Product/LoadAttributes.php
Remove compilation warnings in load attributes code
> DXP-1910 Remove compilation warnings in load attributes code

- src/catalog/Indexer/AttributesIndexer.php
- src/catalog/Model/Indexer/DataLoader/AttributeDataLoader.php
- src/catalog/Model/Indexer/DataLoader/CategoryDataLoader.php
- src/catalog/Model/Indexer/DataLoader/ProductDataLoader.php
- src/core/Api/BasicDataLoader.php
- src/core/Indexer/BaseStreamxIndexer.php
Unify BasicDataLoader contract
> DXP-1910 Unify BasicDataLoader contract

- src/catalog/Indexer/AttributeIndexer.php
- src/catalog/Indexer/CategoryIndexer.php
- src/catalog/Indexer/ProductIndexer.php
- src/core/Indexer/BaseStreamxIndexer.php
- src/core/Indexer/StreamxIndexerServices.php
Group common indexer dependencies into a collective service
> DXP-1823 Group common indexer dependencies into a collective service

- connector-test-endpoints/etc/webapi.xml
- src/catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php
- src/catalog/Model/ResourceModel/Product/Configurable.php
- test/catalog/integration/FullReindexTest.php
Reduce complexity of configurable data provider
> DXP-1910 Reduce complexity of configurable data provider

- src/catalog/Indexer/AttributeIndexer.php
- src/core/Client/StreamxClient.php
- src/core/Indexer/BaseStreamxIndexer.php
- src/core/Indexer/StreamxIndexerServices.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/BaseStreamxTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/BaseMultistoreProductVariantIngestionTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/StreamxConnectorClientLoadTest.php
> DXP-1910 Make StreamxClient stateless

- src/catalog/Model/Attributes/AttributeDefinition.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php
- src/catalog/Model/ResourceModel/Product.php
- src/catalog/Model/ResourceModel/Product/EligibleProductSelectModifier.php
- src/catalog/Model/ResourceModel/Product/Gallery.php
- src/catalog/Model/ResourceModel/Product/IndexedPrices.php
- src/catalog/Model/ResourceModel/Product/LoadAttributeDefinitions.php
- src/catalog/Model/SlugGenerator.php
Various minor cleanups in catalog module
> DXP-1910 Various minor cleanups in catalog module

- src/core/Api/BaseConfigurationManager.php
- src/core/Api/BaseConfigurationReader.php
- src/core/Client/RabbitMQ/RabbitMqMessagesManager.php
- src/core/Client/RabbitMQ/RabbitMqQueuesManager.php
- src/core/Client/StreamxIngestor.php
- test/core/unit/Client/RabbitMQ/IngestionRequestTest.php
- test/core/unit/Client/StreamxClientTest.php
- test/core/unit/Model/Indexer/DataProvider/Category/CategoryDataFormatterTest.php
Various minor cleanups in core module
> DXP-1910 Add tests for generated ingestion keys and sx:types

- .github/workflows/release-as-new-version.yml
Speficy fetch depth when checkouting code
> DXP-1826 Specify fetch depth when checkouting code

- test/catalog/integration/AppEntityUpdateStreamxPublishTests/BaseAppEntityUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/ProductVariantUpdateWhenChangedProductTypeSettingsTest.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductUpdateTest.php
- test/catalog/integration/utils/IngestedKeys.php
- test/catalog/integration/utils/MagentoLogFileUtils.php
Allow verifying how many times a product has been reindexed
> DXP-1934 Allow verifying how many times a product has been reindexed

- src/catalog/Indexer/AttributeIndexer.php
- src/catalog/Model/Attribute/IndexableAttributesFilter.php
- src/catalog/Model/Attributes/BaseProductAttributes.php
- src/catalog/Model/ResourceModel/Product.php
- src/catalog/Plugin/Indexer/Attribute/Save/UpdateAttributeDataPlugin.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeAddAndDeleteTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/AttributeUpdateTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/resources/validation/edited-roller-product.json
- test/resources/validation/original-roller-product.json
Don't reindex products if definition of irrelevant attribute has changed
> DXP-1823 Don't reindex products if definition of irrelevant attribute has changed

- .github/workflows/release-as-new-version.yml
Change bump version commit from amend to new commit
> DXP-1826 Change bump version commit from amend to new commit

- composer.json
- connector-test-endpoints/Impl/StoresControllerImpl.php
- src/catalog/Model/Config/Source/SlugOptionsSource.php
- src/catalog/Model/Indexer/DataProvider/Category/CategoryDataFormatter.php
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/CategoryData.php
- src/catalog/Model/Indexer/DataProvider/Product/ChildProductDataCleaner.php
- src/catalog/Model/Indexer/DataProvider/Product/DataCleaner.php
- src/catalog/Model/SlugGenerator.php
- src/catalog/Model/SystemConfig/CatalogConfig.php
- src/catalog/etc/adminhtml/system.xml
- src/catalog/etc/config.xml
- src/core/System/GeneralConfig.php
- src/core/etc/adminhtml/system.xml
- test/catalog/integration/AppEntityUpdateStreamxPublishTests/CategoryUpdateTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductPublishSlugTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/core/unit/Model/Indexer/DataProvider/Category/CategoryDataFormatterTest.php
- test/core/unit/Model/Indexer/DataProvider/Product/ProductAttributeDataTest.php
Group slug generation options to single choosable config field and fix bug
> DXP-1910 Group slug generation options to single choosable config field and fix bug

- .github/workflows/release-as-new-version.yml
> DXP-1826 Improve github release action

- connector-test-endpoints/Api/ConfigurationEditControllerInterface.php
- connector-test-endpoints/Impl/ConfigurationEditControllerImpl.php
- connector-test-endpoints/etc/webapi.xml
- src/catalog/Model/Indexer/DataProvider/Product/BaseAttributeData.php
- src/catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php
- src/core/Indexer/ImageUrlManager.php
- test/catalog/integration/BaseStreamxConnectorPublishTest.php
- test/catalog/integration/DirectDbEntityUpdateStreamxPublishTests/ProductImageUrlTest.php
- test/catalog/integration/utils/ConfigurationEditUtils.php
- test/catalog/integration/utils/ConfigurationKeyPaths.php
- test/catalog/integration/utils/IngestedKeys.php
- test/catalog/integration/utils/StoreLevelConfigurationEditUtils.php
Fix bug in loading store level base  link urls
> DXP-1368 Fix bug in loading store level base  link urls

- src/core/Client/StreamxClientConfiguration.php
- src/core/Client/StreamxPublisherFactory.php
- src/core/etc/adminhtml/system.xml
- src/core/etc/config.xml
- test/catalog/integration/BaseStreamxTest.php
Introduce configurable timeouts to the ingestion endpoint
> SXPR-116 Introduce configurable timeouts to the ingestion endpoint
